### ISSUE TITLE
Two pairs of same image

### ISSUE THREAD

**Issue by goldencut** [SecUSo/privacy-friendly-memo-game#10]
Game in easy mode, had two pairs of monkeys, but only certain two paired together.

**Comment by Yonjuni** [comment]
There are two monkeys in that deck that look very similar. Those are [here](https://github.com/SecUSo/privacy-friendly-memo-game/blob/master/app/src/main/res/drawable/set2card20.png) and [here](https://github.com/SecUSo/privacy-friendly-memo-game/blob/master/app/src/main/res/drawable/set2card19.png).

Could it be that those two were in the game? We have tested and in our tests the problem did not occur.
