### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [SecUSo/privacy-friendly-memo-game#12]
Hi @SecUSo

I found [this app ](https://play.google.com/store/apps/details?id=com.game.PuzzleMemory) on the Google Play Store. This guys just took the source code, added some ads and put it on the Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 and this guy is violating it by distributing the app without distributing the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by Yonjuni** [comment]
@Poussinou He also copied our [QR-Code-Scanner-App](https://github.com/SecUSo/privacy-friendly-qr-scanner) [here ](https://play.google.com/store/apps/details?id=com.topmobile.QRCodeScanner)

**Comment by Poussinou** [comment]
Yep, that's right... In fact most of his apps are open-sourced apps, but with ads in it. I'm currently looking for the authors of the free applications and warn them...
Please report both apps to Google using the link I gave you earlier

**Comment by Poussinou** [comment]
THe app is now down, I close this Issue.

Do not hesitate to reopen it if you find any other new copyright violation !

**Comment by Yonjuni** [comment]
Thanks :)

**Comment by Poussinou** [comment]
Another one [here](https://play.google.com/store/apps/details?id=org.secuso.memorygame.ui).

**Comment by Kamuno** [comment]
This one is down as well. I will close this issue for now.
