### ISSUE TITLE
When score is below highscore, it is not shown at the end of the game.

### ISSUE THREAD

**Issue by absorber** [SecUSo/privacy-friendly-memo-game#21]
Instead it is shown as "Highscore: 0"

**Comment by hanneshofmann** [comment]
As far as I recall, the scored points are shown even when it is below the current highscore. 'Highscore: 0' is shown when the score is 0 or below 0 (keep in mind: the score is calculated based on the time and the amount of attempts to finish the game, hence it may be 0 or below).
